title: Period
tagline: "Period removes the burden of working with time ranges in PHP"
description: "Period provides an immutable value object to ease working with Time Ranges"
google_analytics_tracking_id: UA-46050814-11